spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:database}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}
  
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
